### PR TITLE
Added random password generator API

### PR DESCRIPTION
**Pull request by Sampahcokk-dev**
## Description

Added random password generator API for hacktoberfest 2021

## Screenshot 
Optional

<hr>
Checklist

- [x] API used in this PR was not used in Random-APIs before.
- [x] API used in this PR is Public or I have permission to use it.
- [x] My contribution is working.
- [x] My changes don't generate any new warnings.
- [x] My changes don't affect any work done by other developers. 

To tick a box, replace `[ ]` with `[x]`.

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
@Sampahcokk-dev 
There is already a pending PR that uses the same API

**Comment by Sampahcokk-dev** [comment]
> @Sampahcokk-dev 
> There is already a pending PR that uses the same API

ooh sorry

**Comment by Sampahcokk-dev** [comment]
so should i close this pull request? sorry beginner here

**Comment by ashutoshkrris** [comment]
> so should i close this pull request? sorry beginner here

Yes, you can close this one, and if you wish you can create another PR with some different API

**Pull request closed without merging**
