### PR TITLE
Added Fun Facts API

### PR DESCRIPTION
**Pull request by surya-doc**
## Description

This API will show some random fun facts.

## Screenshot 
1st-hackt_21

<hr>
Checklist

- [x] API used in this PR was not used in just-calling-random-api before.
- [x] API used in this PR is Public or I have permission to use it.
- [x] My contribution is working.
- [x] My changes don't generate any new warnings.
- [x] My changes don't affect any work done by other developers.

### CODE REVIEW

**Comment by surya-doc** [comment]
Added Fun Fact API.

**Comment by ashutoshkrris** [comment]
@surya-doc Could you please verify if https://asli-fun-fact-api.herokuapp.com/ works for you

**Comment by surya-doc** [comment]
@ashutoshkrris yes [https://asli-fun-fact-api.herokuapp.com/](https://asli-fun-fact-api.herokuapp.com/) this API is working for me.

**Comment by ashutoshkrris** [comment]
Yes, now it's working fine.
Earlier it didn't return anything

**Comment by surya-doc** [comment]
Ok.

**Pull request merged**
