### PR TITLE
Add covid data global cases API

### PR DESCRIPTION
**Pull request by Sampahcokk-dev**
## Description

Added global covid data cases API for hacktoberfest 2021

## Screenshot 
image

Optional

<hr>
Checklist

- [x] API used in this PR was not used in Random-APIs before.
- [x] API used in this PR is Public or I have permission to use it.
- [x] My contribution is working.
- [x] My changes don't generate any new warnings.
- [x] My changes don't affect any work done by other developers. 

To tick a box, replace `[ ]` with `[x]`.

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
Hey @Sampahcokk-dev 
Please add the `loading` line in the code. You can find the updated code in README.
Please also add screenshot of the output.

**Comment by Sampahcokk-dev** [comment]
so should i close this pull request?

**Comment by ashutoshkrris** [comment]
No @Sampahcokk-dev 
You need not close this..
You can simply commit your changes and open pull request. It will be added to this PR only

**Comment by Sampahcokk-dev** [comment]
ok done

**Pull request merged**
